//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bot4331
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dialog_Info
    {
        public int Id { get; set; }
        public int Id_word_users { get; set; }
        public int Id_word_bot { get; set; }
    
        public virtual word_bot word_bot { get; set; }
        public virtual word_users word_users { get; set; }
    }
}
