//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bot4331
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationTablesValues
    {
        public int id { get; set; }
        public string name { get; set; }
        public int idTable { get; set; }
        public string description { get; set; }
    
        public virtual InformationTalbes InformationTalbes { get; set; }
    }
}
