//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bot4331
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ryzhkin_botEntities : DbContext
    {
        public Ryzhkin_botEntities()
            : base("name=Ryzhkin_botEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Dialog_Info> Dialog_Info { get; set; }
        public virtual DbSet<InformationTablesValues> InformationTablesValues { get; set; }
        public virtual DbSet<InformationTalbes> InformationTalbes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<word_bot> word_bot { get; set; }
        public virtual DbSet<word_users> word_users { get; set; }
        public virtual DbSet<InformationClient> InformationClient { get; set; }
        public virtual DbSet<YesOrNo> YesOrNo { get; set; }
        public virtual DbSet<usersApplications> usersApplications { get; set; }
    }
}
