//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bot4331
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersApplications
    {
        public int id { get; set; }
        public string applications { get; set; }
        public string name { get; set; }
        public Nullable<long> idChat { get; set; }
        public string condition { get; set; }
        public string number { get; set; }
        public string FirstName { get; set; }
    }
}
